apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-dp
  labels:
    app: kuber-dp
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: kuber-app
          image: armanbektassov/users-app:5.2
          ports:
            - containerPort: 4567
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_port
          envFrom:
            - configMapRef:
                name: env-config
          livenessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 20
            periodSeconds: 5