apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rmq.name }}
spec:
  selector:
    app: {{ .Values.rmq.name }}
  ports:
    - name: amqp
      port: {{ .Values.rmq.service.port }}
      targetPort: {{ .Values.rmq.service.port }}
    - name: management
      port: 15672
      targetPort: 15672
  type: {{ .Values.rmq.service.type }}
