{
 "title": "Users-app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{path!=\"/metrics\", path!=\"/favicon.ico\", path!=\"/health\"}[10m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{service=\"users-app-users-chart\"}[10m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    0.99,\n    sum(rate(http_server_request_duration_seconds_bucket{path!=\"/metrics\", path!=\"/favicon.ico\", path!=\"/health\"}[10m])) by (le, path)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    0.99,\n    sum(rate(http_server_request_duration_seconds_bucket{service=\"users-app-users-chart\"}[10m])) by (le, service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    0.95,\n    sum(rate(http_server_request_duration_seconds_bucket{path!=\"/metrics\", path!=\"/favicon.ico\", path!=\"/health\"}[10m])) by (le, path)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency service 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    0.95,\n    sum(rate(http_server_request_duration_seconds_bucket{service=\"users-app-users-chart\"}[10m])) by (le, service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    0.50,\n    sum(rate(http_server_request_duration_seconds_bucket{path!=\"/metrics\", path!=\"/favicon.ico\", path!=\"/health\"}[10m])) by (le, path)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency service 0.50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    0.50,\n    sum(rate(http_server_request_duration_seconds_bucket{service=\"users-app-users-chart\"}[10m])) by (le, service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    1.00,\n    sum(rate(http_server_request_duration_seconds_bucket{path!=\"/metrics\", path!=\"/favicon.ico\", path!=\"/health\"}[10m])) by (le, path)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency service max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(    \n    1.00,\n    sum(rate(http_server_request_duration_seconds_bucket{service=\"users-app-users-chart\"}[10m])) by (le, service)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total{path!=\"/metrics\", code=~\"4.*|5.*\"}[10m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total{path!=\"/metrics\", code=~\"4.*|5.*\"}[10m]))/sum(increase(http_server_requests_total{path!=\"/metrics\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}