apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}-service
spec:
  selector:
    app: {{ .Values.gateway.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      name: http
  type: {{ .Values.gateway.service.type }}