apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storage.name }}-service
spec:
  selector:
    app: {{ .Values.storage.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.storage.service.port }}
      targetPort: {{ .Values.storage.service.targetPort }}
      name: http
  type: {{ .Values.storage.service.type }}