apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    management.tcp.port = 15672
    management.load_definitions = /etc/rabbitmq/definitions.json
    prometheus.tcp.port = 15692
    loopback_users.guest = false
    plugins.expand = rabbitmq_management rabbitmq_prometheus
