source 'https://rubygems.org'

gem "sinatra"
gem "activerecord"
gem "rake"
gem "sinatra-activerecord", '~> 2.0'
gem 'bigdecimal'
gem 'bunny'
gem 'rest-client'

group :production, :development, :test do
  gem 'pg', '~> 0.15'
end
