apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.billing.name }}-migrate
  labels:
    app: {{ .Values.billing.name }}-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: "{{ .Values.billing.image.repository }}:{{ .Values.billing.image.tag }}"
          command:
            - rake
            - db:create
            - db:migrate
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_name_billing
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: database_port
      restartPolicy: Never