gateway:
  name: gateway-app
  image:
    repository: armanbektassov/hw7_gateway
    tag: "1.2"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

account:
  name: account-app
  image:
    repository: armanbektassov/hw7_account
    tag: "1.0"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

billing:
  name: billing-app
  image:
    repository: armanbektassov/hw7_billing
    tag: "1.4"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

order:
  name: order-app
  image:
    repository: armanbektassov/hw7_order
    tag: "1.3"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

notification:
  name: notification-app
  image:
    repository: armanbektassov/hw7_notification
    tag: "1.2"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

postgres:
  name: postgres
  image:
    repository: postgres
    tag: "14"
  replicas: 1
  service:
    type: NodePort
    port: 5432

rmq:
  name: rabbitmq
  image:
    repository: rabbitmq
    tag: "management"
  replicas: 1
  service:
    type: ClusterIP
    port: 5672

ingress:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80