apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type:  {{ .Values.postgresService.type }}
  ports:
    - port: {{ .Values.postgresService.port }}
  selector:
    app: postgres