apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-chart.fullname" . }}-users
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "auth-chart.fullname" . }}-users
    {{- include "auth-chart.selectorLabels" . | nindent 4 }}
