source 'https://rubygems.org'

gem "sinatra"
gem "activerecord"
gem "rake"
gem "sinatra-activerecord", '~> 2.0'
gem 'bigdecimal'
gem "prometheus-client"
gem "bcrypt"

group :production, :development, :test do
  gem 'pg', '~> 0.15'
end
