gateway:
  name: gateway-app
  image:
    repository: armanbektassov/hw8_gateway
    tag: "1.6"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

account:
  name: account-app
  image:
    repository: armanbektassov/hw8_account
    tag: "1.0"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

billing:
  name: billing-app
  image:
    repository: armanbektassov/hw8_billing
    tag: "1.5"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

order:
  name: order-app
  image:
    repository: armanbektassov/hw8_order
    tag: "3.2"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

order_worker:
  name: order-worker-app
  image:
    repository: armanbektassov/hw8_order_worker
    tag: "1.3"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

delivery:
  name: delivery-app
  image:
    repository: armanbektassov/hw8_delivery
    tag: "1.8"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

kitchen:
  name: kitchen-app
  image:
    repository: armanbektassov/hw8_kitchen
    tag: "1.0"
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 4567

postgres:
  name: postgres
  image:
    repository: postgres
    tag: "14"
  replicas: 1
  service:
    type: NodePort
    port: 5432

rmq:
  name: rabbitmq
  image:
    repository: rabbitmq
    tag: "management"
  replicas: 1
  service:
    type: ClusterIP
    port: 5672

prometheus:
  server:
    service:
      type: NodePort
      nodePort: 30090
    persistentVolume:
      enabled: true
      size: 10Gi
    global:
      scrape_interval: 15s

grafana:
  adminPassword: "admin"
  service:
    type: NodePort
    nodePort: 30300
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: manual
    accessModes:
      - ReadWriteOnce

ingress:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80