apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rmq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rmq.name }}
    spec:
      containers:
        - name: {{ .Values.rmq.name }}
          image: "{{ .Values.rmq.image.repository }}:{{ .Values.rmq.image.tag }}"
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
            - name: prometheus
              containerPort: 15692
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_CONFIG_FILE
              value: /etc/rabbitmq/config/rabbitmq.conf
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: config
              mountPath: /etc/rabbitmq/config
              subPath: rabbitmq.conf
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: config
          configMap:
            name: rabbitmq-config
